# Generated by Django 4.2.5 on 2023-09-05 13:15

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')
        if ( DJANGO_SU_NAME == None or
             DJANGO_SU_EMAIL == None or
             DJANGO_SU_PASSWORD == None
           ):
               raise ValueError("environment variables DJANGO_SU_NAME, DJANGO_SU_EMAIL and DJANGO_SU_PASSWORD net to be set") 

        # only add the superuser if no other user exists
        users = User.objects.all()
        if not users:
            superuser = User.objects.create_superuser(
                username=DJANGO_SU_NAME,
                email=DJANGO_SU_EMAIL,
                password=DJANGO_SU_PASSWORD)

            superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
