# Generated by Django 4.2.5 on 2023-09-05 14:53

from django.db import migrations

def add_welcome_messages(apps, schema_editor):
    WelcomeMessage = apps.get_model("index", "WelcomeMessage")
    for msg in ["Welcome to deplo.io", "Deployments made easy", "This is a sample Django app"]:
        temp = WelcomeMessage(text=msg)
        temp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_initial'),
    ]

    operations = [
            migrations.RunPython(add_welcome_messages),
    ]
